waltid-did/src/jvmTest/kotlin/TestServer.kt
waltid-did/src/jvmTest/kotlin/resolvers/UniResolverTest.kt

Files were not being found because of white spaces encoded in the file path.
`val encodedPath = Companion::class.java.classLoader.getResource("uniresolver/jwk/document.json").path`
results in
```
/dir%20with%20white%20spaces/coding/waltid-identity/waltid-did/build/processedResources/jvm/test/uniresolver/jwk/document.json
```
whereas 
```
URI(encodedPath).toString().path
```
returns 
```
/dir with white spaces/coding/waltid-identity/waltid-did/build/processedResources/jvm/test/uniresolver/jwk/document.json
```
Another possible solution could be
```
URLDecoder.decode(encodedPath, "UTF-8")
```

Fixing failing DID tests by FileNotFoundException

---

waltid-crypto/src/jvmTest/kotlin/TestUtils.kt

Fixed resource loading so that it works when there are blank spaces in the directory name hierarchy.

fix: resource loading with blank spaces in the path

---

docker-compose/.env

In the docker compose .env file, the `DATABASE_ENGINE` variable is set to a value which includes the whitespace and the comment, on some systems.
Move the comment above the variable.

fix docker compose env comment

---

waltid-libraries/waltid-crypto/src/commonMain/kotlin/id/walt/crypto/keys/Key.kt
waltid-libraries/waltid-mdoc-credentials/README.md
waltid-libraries/waltid-mdoc-credentials/build.gradle.kts
waltid-libraries/waltid-openid4vc/README.md
waltid-libraries/waltid-openid4vc/build.gradle.kts
waltid-libraries/waltid-sdjwt/README.md
waltid-libraries/waltid-sdjwt/build.gradle.kts
waltid-services/waltid-issuer-api/build.gradle.kts
waltid-services/waltid-service-commons/README.md
waltid-services/waltid-service-commons/build.gradle.kts
waltid-services/waltid-verifier-api/build.gradle.kts

- All artifacts for the packages for mdocs, openid4vc, sdjwt were grouped together in the maven repo.
- Package waltid-service-commons is not also published to maven and can be used as dependency.

Refactore maven publishing structure

---

waltid-applications/waltid-web-portal/pages/success/[sessionId].tsx

The backend response for the verification session result was updated: the "policies" key was renamed to "policyResults". The frontend still looks for "policies," causing a rendering error since it no longer exists.

fix: Portal verification success page rendering

---

waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/db/models/WalletCredentials.kt

When kotlin-exposed attempts to add the missing table / columns (format column for wallet-credentials table), it fails for tables that already have records.
This hotfix sets the wallet-credential format column to have a default value - `CredentialFormat.jwt_vc_json`.
Since the wallet-api couldn't claim until now other credential types than jwt and sdjwt, this solution is safe (both being covered by the aforementioned format). But a proper solution would be introducing a db migration strategy.

hotfix: set wallet credential format column default value

---

waltid-services/waltid-wallet-api/config/registration-defaults.conf
waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/config/RegistrationDefaultsConfig.kt
waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/account/AccountsService.kt
waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/issuers/IssuerDataTransferObject.kt
waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/issuer/IssuerUseCaseImpl.kt

Description
Default issuer can be configured through registration-defaults.conf file. Also, this PR fixes the problem with wallet-api not being able to properly process the supported credentials due to response change in https://issuer.portal.walt.id/.well-known/openid-credential-issuer endpoint.
Fixes #462

feat: Default issuer configurable in wallet-api

---

waltid-applications/waltid-web-portal/pages/verify/index.tsx
waltid-libraries/sdjwt/waltid-sdjwt/build.gradle.kts
waltid-libraries/sdjwt/waltid-sdjwt/src/commonMain/kotlin/id/walt/sdjwt/SDJwtVC.kt
waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/config/CredentialTypeConfig.kt
waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/CIProvider.kt

resolve "verification policies did not succeed: signature_sd-jwt-vc" error. Verifier expects 'kid' in the cnf JWK object – enforce 'kid' in cnf when issuing credentials
fixes WAL-398
fixes WAL-419
- \-

WAL 398 | verification policies did not succeed: signature_sd-jwt-vc

---

waltid-services/waltid-issuer-api/k8s/deployment-dev.yaml
waltid-services/waltid-issuer-api/k8s/deployment-prod.yaml

Removes and cleans up the credential-issuer-metadata config from deployments, using by default the values from [CredentialTypeConfig](https://github.com/walt-id/waltid-identity/blob/main/waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/config/CredentialTypeConfig.kt). Fixes wal-440.
- \-

ci: remove credential-issuer-metadata config for dev + prod env

---

waltid-applications/waltid-cli/src/jvmTest/kotlin/id/walt/cli/commands/WaltIdDidCreateCmdTest.kt

The build process was failing on my local environment. The reason was a failing unit test. 
```
> Task :waltid-applications:waltid-cli:jvmTest
WaltIdDidCreateCmdTest[jvm] > should succeed creating a DID key using jwk_jcs-pub with all key types()[jvm] FAILED
org.opentest4j.AssertionFailedError at WaltIdDidCreateCmdTest.kt:197
```
- [ x ] bug fix - change which fixes an issue
- [ x ] code cleanup and self-review
- [ x ] unit + e2e test coverage
- [ x ] documentation updated accordingly
No.
- \-

Fixing broken test in the CLI

---

.github/workflows/test-deploy.yml

Updates test-deployment github action to allow the provision of custom release-version.
- \-

ci: add optional release-version input for test-deployment

---

.run/Issuer.run.xml
waltid-libraries/credentials/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/issuance/Issuer.kt
waltid-libraries/credentials/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/schemes/JwsSignatureScheme.kt
waltid-libraries/credentials/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/vc/vcs/W3CVC.kt
waltid-libraries/credentials/waltid-verifiable-credentials/src/commonTest/kotlin/LocalVcAPITest.kt
waltid-services/waltid-e2e-tests/src/test/kotlin/E2ESdJwtTest.kt
waltid-services/waltid-e2e-tests/src/test/kotlin/WaltidServicesE2ETests.kt

fix w3c payload scheme if issued as sd-jwt (wal-368)
add e2e test check to verify vc sub-property
fix issuer ID, kid and subject id in w3c sd-jwts
- \-

fix w3c payload scheme if issued as sd-jwt.

---

waltid-libraries/crypto/waltid-crypto/src/commonMain/kotlin/id/walt/crypto/exceptions/CryptoExceptions.kt

It is always a "best pattern" to allow attaching an original cause when throwing new exceptions.
For example, a KeyNotFoundException in a given Key implementation can be due to different original causes (network error, hardware error, HSM quota exceeded,  ...). Allowing to "attach" the original cause avoids to loose "precious" information to the "sysops" team trying to fix the error in a production environments.
(Unit test did work, e2e test missing -But I guess the change is backward compatible, just adding an optional parameter-)
- [X ] new feature - change which adds functionality
- \-

Best-pattern: allow to attach 'cause' (detail) to new exception

---

waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletServiceManager.kt

- loads trust-config when silent-exchange feature is enabled (the feature that makes the config mandatory)
fixes wal-778
fixes #858 
- \-

fix: load trust-config when feature is enabled

---

.github/actions/gradle-setup-action/action.yml
.github/workflows/build.yml
.github/workflows/gradle.yml
.github/workflows/pre-release.yml
.github/workflows/release.yml
.github/workflows/test-deploy.yml

- reorders gradle setup and wrapper validation within the composite gradle-setup-action
- fixes action reference in the gradle workflow to full path
- updates gradle workflow references
relates to WAL-839
- \-

fix: gradle workflow reference in build

---

build.gradle.kts
waltid-libraries/credentials/waltid-mdoc-credentials/build.gradle.kts
waltid-libraries/credentials/waltid-mdoc-credentials/src/jvmMain/kotlin/id/walt/mdoc/COSECryptoProviderKeyInfo.kt
waltid-libraries/credentials/waltid-mdoc-credentials/src/jvmMain/kotlin/id/walt/mdoc/SimpleCOSECryptoProvider.kt
waltid-libraries/credentials/waltid-mdoc-credentials/src/jvmTest/kotlin/id/walt/mdoc/JVMMdocTest.kt
waltid-libraries/protocols/waltid-openid4vc/build.gradle.kts
waltid-libraries/protocols/waltid-openid4vc/src/jvmMain/kotlin/id/walt/oid4vc/util/COSESign1Utils.jvm.kt
waltid-libraries/protocols/waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/MDoc_Test.kt
waltid-libraries/waltid-core-wallet/build.gradle.kts
waltid-libraries/waltid-core-wallet/src/jvmMain/java/id/walt/wallet/core/service/exchange/ProofOfPossessionFactory.kt
waltid-libraries/waltid-core-wallet/src/jvmMain/java/id/walt/wallet/core/service/exchange/ProofOfPossessionParameterFactory.kt
waltid-libraries/waltid-core-wallet/src/jvmMain/java/id/walt/wallet/core/service/oidc4vc/TestCredentialWallet.kt
waltid-services/waltid-e2e-tests/build.gradle.kts
waltid-services/waltid-e2e-tests/src/test/kotlin/AuthApi.kt
waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeExternalSignaturesApi.kt
waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialIssuance.kt
waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialVerification.kt
waltid-services/waltid-issuer-api/build.gradle.kts
waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/CIProvider.kt
waltid-services/waltid-issuer-api/src/test/kotlin/id/walt/LspPotentialTest.kt
waltid-services/waltid-verifier-api/build.gradle.kts
waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/lspPotential/LspPotentialVerificationInterop.kt
waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/oidc/OIDCVerifierService.kt
waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/oidc/VerificationUseCase.kt
waltid-services/waltid-wallet-api/build.gradle.kts
waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/ProofOfPossessionFactory.kt
waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/ProofOfPossessionParameterFactory.kt
waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt
waltid-services/waltid-wallet-api/src/test/kotlin/id/walt/webwallet/service/credentials/status/fetch/DefaultStatusListCredentialFetchStrategyTest.kt

The cose-java library has been updated to use the newer fork from: https://github.com/sbahloul/cose-java
The cose-java library was build on my side, with an updated version of the bouncycastle libraries, "org.bouncycastle:bcprov-lts8on:2.73.7" and "org.bouncycastle:bcpkix-lts8on:2.73.7", to comply with the versions used on our waltid-identity stack and to fix the test errors, that would have broken the build with the conflicting bouncycastle versions.
I uploaded a custom build of the cose-java library to our maven snapshots repository: 
"https://maven.waltid.dev/snapshots".

Wal 1039 cose lib upgrade

---

waltid-libraries/credentials/waltid-verification-policies/src/jvmMain/kotlin/id/walt/policies/policies/RevocationPolicy.jvm.kt

This PR addresses the Redis serialization issue described in [walt-id/waltid-identity#993](https://github.com/walt-id/waltid-identity/issues/993) by marking the logger in `RevocationPolicy.kt` as `@Transient`.

Making logger being transient and excluded from serialization flow

---

waltid-services/waltid-e2e-tests/src/test/kotlin/WaltidServicesE2ETests.kt

fix: comment out lsp tests (mdocs) with expired x.509

---

docker-compose/README.md
docker-compose/docker-compose.yaml

The `wallet-api/walt.yaml` file does not exists and is not used anymore. I think this is old configuration.

Remove walt.yaml mapping in docker compose configuration

---

waltid-libraries/credentials/waltid-verification-policies/src/commonMain/kotlin/id/walt/policies/policies/SdJwtVCSignaturePolicy.kt

Fixes `SdJwtVCSignaturePolicy` verify method to return `Result<JsonElement>` instead of `Result<Result<JsonElement>>` for successful verification in the _credential_ conditional branch following https://github.com/walt-id/waltid-identity/pull/986 updates. Returning `Result<Result<*>>` fails the JSON conversion in [JsonUtils](https://github.com/walt-id/waltid-identity/blob/168dbdae307540e87d4ce04c0902698f6052f0ec/waltid-libraries/crypto/waltid-crypto/src/commonMain/kotlin/id/walt/crypto/utils/JsonUtils.kt#L15) when called by [PolicyResultSurrogate](https://github.com/walt-id/waltid-identity/blob/f47e1c2bd6bdd45a43bb4f93499580d8888c12ee/waltid-libraries/credentials/waltid-verification-policies/src/commonMain/ko …

fix: verification result return type for sd-jwt-vc-signature-policy credential branch

---

docker-compose/wallet-api/config/registration-defaults.conf
waltid-services/waltid-wallet-api/config/registration-defaults.conf
waltid-services/waltid-wallet-api/k8s/deployment-dev.yaml
waltid-services/waltid-wallet-api/k8s/deployment-prod.yaml

Changed default key type for new registered users to secp256r1. This allows new users also to put mDL and mDocs credentials into their wallet.
- \-

feat: [WAL-1592] Set Web Wallet default key type secp256r1

---

.github/workflows/build.yml
.github/workflows/docker-compose-testing.yml

Updates the compose-testing workflow, which is required following the updates from #1197 
- \-

fix: cicd compose testing to use the localhost postman environment

---

waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/OpenID4VC.kt

- use private key's jws-alg in `signToken`
- \-

fix: replace hardcoded alg claim from sign-token with private key jws-alg
