waltid-web-wallet/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt
publish wallet backend api
fix issuer parse issue
=> New stack docker compose

waltid-wallet-api/k8s/deployment-dev.yaml
fix oidc config in k8s dev deployment
=> fix dev wallet deployment with keycloak configuration

waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/responses/EntraIssuanceCompletionResponse.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/CI_JVM_Test.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/exchange/IssuanceService.kt
Successfully send and receive entra issuance callback, in issuance test
=> Entra callback test

waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/BitStringValueParser.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/JwsDecoder.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/credentials/CredentialValidator.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/credentials/status/StatusListCredentialStatusService.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/endpoint/EntraServiceEndpointProvider.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/utils/Utils.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/CredentialController.kt, waltid-wallet-api/src/test/kotlin/id/walt/webwallet/utils/StreamUtilsTest.kt
- jwt payload reference
- bitstring value url-decode
- missing credential type in credential validator
- endpoint provider request content negotiation
- status endpoint return type
=> fix: credential status

waltid-did/src/commonMain/kotlin/id/walt/did/dids/resolver/local/DidWebResolver.kt, waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/notification/NotificationDataFormatter.kt
- did web resolver response parsing
- remove version from credential name when displayed as notification message
=> various fixes

docker-compose/Caddyfile, docker-compose/docker-compose.yaml
=> set always pull policy

waltid-sdjwt/build.gradle.kts, waltid-sdjwt/src/commonTest/kotlin/id/walt/sdjwt/SDJwtTest.kt, waltid-sdjwt/src/iosTest/kotlin/id.walt.sdjwt/SDJwtTestIOS.kt, waltid-sdjwt/src/jsTest/kotlin/id.walt.sdjwt/SDJwtTestJS.kt, waltid-sdjwt/src/jvmTest/kotlin/id/walt/sdjwt/SDJwtTestJVM.kt
=> proposal replace sdjwt kotest assertions

waltid-openid4vc/build.gradle.kts, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/CITestProvider.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/CI_JVM_Test.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/EBSITestWallet.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/EBSI_Conformance_Test.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/EBSI_Issue_To_Holder.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/TestCredentialWallet.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/VPTestVerifier.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/VP_JVM_Test.kt, waltid-openid4vc/src/jvmTest/kotlin/id/walt/oid4vc/wallettest.kt
=> proposal replace openid4vc kotest assertions

waltid-libraries/waltid-crypto/src/jvmMain/kotlin/id/walt/crypto/keys/JWKKeyGenerator.jvm.kt, waltid-libraries/waltid-crypto/src/jvmTest/kotlin/ImportJWKKeyTestsAndDidManagement.kt, waltid-libraries/waltid-did/src/jvmTest/kotlin/resolvers/DidKeyResolverTest.kt
This contains the rsa related commits from https://github.com/walt-id/waltid-identity/pull/544
- 3fea3899cedc67eabe23806af9ea1687f2afc149
- 6d9c0f703ced6a8e9c7660803a86da66eee9288f
- 5bd8391e5059eaee7fa87c56720665007bae0fb8
=> Support import raw RSA public key

waltid-libraries/waltid-crypto/src/jvmMain/kotlin/id/walt/crypto/keys/jwk/JWKKey.jvm.kt, waltid-libraries/waltid-did/src/commonTest/kotlin/id/walt/did/localresolvers/DidKeySimpleTests.kt
This contains the ec import public raw fix related commits from https://github.com/walt-id/waltid-identity/pull/544:
- 632a4722e9c405f6dbc6497973c26819618e38b4
- 7f7d0f9febb7ad06cff2d2369d474995f432c33e
=> [PRO-784] Fix secp256k1 and secp256r1 raw public key encoding

waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETest.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETestWebService.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/KeyAssertions.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/KeyTests.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/KeysApi.kt, waltid-services/waltid-e2e-tests/src/test/resources/keys/rsa.json, waltid-services/waltid-e2e-tests/src/test/resources/keys/secp256r1.json
Adds keys api contract tests as part of the e2e test suite.
Fixes #424
=> 424 wallet add missing key e2e tests

waltid-applications/waltid-web-wallet/src/components/credentials/VerifiableCredentialCard.vue
=> chore: Added support for validity period from data-model v2.0

waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/dids/DidService.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/AuthController.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/DidController.kt
Remove transaction block from services and controller
=> Fix transaction block in did listing

waltid-applications/waltid-cli/README.md, waltid-libraries/waltid-crypto/README.md, waltid-libraries/waltid-did/README.md, waltid-libraries/waltid-sdjwt/README.md, waltid-services/waltid-issuer-api/README.md, waltid-services/waltid-service-commons/README.md, waltid-services/waltid-verifier-api/README.md, waltid-services/waltid-wallet-api/README.md
Updated Readme files 
Fixes #576
=> Fix readme files

waltid-libraries/waltid-did/src/jvmTest/kotlin/resolvers/UniResolverTest.kt
Remove stale universal resolver test cases.
Fixes #595
=> fix: universal resolver stale test cases

waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/IssuerApi.kt
=> fix: issuer-api raw jwt sign response vc field

waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/IssuanceExamples.kt, waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/IssuerApi.kt, waltid-services/waltid-service-commons/src/main/kotlin/id/walt/commons/web/modules/OpenApiModule.kt
=> release hot-fixes

waltid-libraries/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/requests/CredentialRequest.kt
=> fix: allow unknown keys in json for interoperability

waltid-libraries/waltid-crypto/src/jvmMain/kotlin/id/walt/crypto/keys/JWKKeyGenerator.jvm.kt, waltid-libraries/waltid-crypto/src/jvmTest/kotlin/ImportJWKKeyTestsAndDidManagement.kt
=> Fix raw import of secp256k1 and secp256r1 keys

waltid-libraries/waltid-verifiable-credentials/build.gradle.kts, waltid-libraries/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/Claims.kt, waltid-libraries/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/verification/DatePolicyUtils.kt, waltid-libraries/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/verification/policies/ExpirationDatePolicy.kt, waltid-libraries/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/verification/policies/NotBeforeDatePolicy.kt, waltid-libraries/waltid-verifiable-credentials/src/jvmTest/kotlin/id/walt/credentials/verification/policies/DatePolicyTestBase.kt, waltid-libraries/waltid-verifiable-credentials/src/jvmTest/kotlin/id/walt/credentials/verification/policies/ExpirationDatePolicyTest.kt, waltid-libraries/waltid-verifiable-credentials/src/jvmTest/kotlin/id/walt/credentials/verification/policies/NotBeforeDatePolicyTest.kt
Adds `validFrom` handling for `NotBeforeDatePolicy`. Adds tests for `NotBeforeDatePolicy` and `ExpirationDatePolicy`. Adds `DatePolicyUtils` for shared functionality.
Fixes #559
=> 559 missing support for validity start date from vc data model v20

.github/workflows/pre-release.yml, .github/workflows/release.yml
Bumps github pre-release and release workflows changelog job version.
=> ci: bump changelog job version

waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/providers/OpenIDCredentialWallet.kt, waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/providers/OpenIDProvider.kt, waltid-services/waltid-e2e-tests/config/_features.conf, waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETest.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeApi.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeExternalSignaturesApi.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialWallet.kt, waltid-services/waltid-wallet-api/config/_features.conf, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/FeatureCatalog.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/Main.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletService.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/CredentialFilterUtils.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/oidc4vc/TestCredentialWallet.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/ExchangeExternalSignaturesController.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeController.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeExternalSignaturesController.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/OpenAPICommons.kt
=> feat: define optional and disabled by default external signature endpoints feature

waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt
Fixes #702 
Note : this pr should be merged after #705
=> fix: improve displaying of error in usePresentationRequest endpoint

waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/src/pages/signup.vue, waltid-applications/waltid-web-wallet/apps/waltid-dev-wallet/src/pages/signup.vue
=> fix: update registration endpoint

build.gradle.kts, waltid-applications/waltid-web-portal/components/sections/VerificationSection.tsx, waltid-applications/waltid-web-portal/components/walt/credential/RowCredential.tsx, waltid-applications/waltid-web-portal/pages/success/[sessionId].tsx, waltid-applications/waltid-web-portal/pages/verify/index.tsx, waltid-applications/waltid-web-portal/types/credentials.tsx, waltid-applications/waltid-web-portal/utils/getOfferUrl.tsx, waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialVerification.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialWallet.kt, waltid-services/waltid-e2e-tests/src/test/resources/presentation/batch-openbadge-universitydegree-presentation-request.json, waltid-services/waltid-e2e-tests/src/test/resources/presentation/openbadgecredential-presentation-request.json, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/VerifierApi.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/VerifierApiExamples.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/oidc/OIDCVerifierService.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/oidc/RequestedCredential.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/oidc/VerificationUseCase.kt
Changes described in internal roadmap issue #29: 
https://github.com/walt-id/roadmap-int/issues/29
=> Roadmap 29 verifier api

docker-compose/docker-compose.yaml
=> add: env variables for wallet links

waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/src/pages/wallet/[wallet]/exchange/presentation.vue
=> fix: Wallet multiple presentation scroll view

waltid-applications/waltid-web-wallet/libs/composables/presentation.ts, waltid-libraries/credentials/waltid-verifiable-credentials/src/commonMain/kotlin/id/walt/credentials/verification/Verifier.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/VerifierApi.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/oidc/VerificationUseCase.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/utils/Utils.kt
Includes:
- docker-compose changes by sevi
- fix: handle presentation screen issues regarding no matched credentials
- check if error is JSON message before trying to parse as JSON
- fix: error handling on failed policies
- various smaller ones to fix other issues
=> Fix wallet presentation errors

waltid-libraries/waltid-did/README.md
=> docs: fix did doc config example in did lib README.md

waltid-services/waltid-e2e-tests/src/test/kotlin/AuthorizationCodeFlow.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/DidsApi.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/E2ESdJwtTest.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETest.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/E2ETestWebService.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeApi.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeExternalSignaturesApi.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/IssuerApi.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialWallet.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/VerifierApi.kt, waltid-services/waltid-e2e-tests/src/test/resources/issuance/disclosure.json, waltid-services/waltid-e2e-tests/src/test/resources/presentation/openbadgecredential-name-field-presentation-request.json
=> 643 issuance verification tests for w3c sd jwt

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
Updates github pr and new issue templates.
=> chore: update pr and issue templates

waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/CIProvider.kt
=> WAL-397 | Batch claiming issues the same credential

waltid-applications/waltid-web-portal/pages/success/[sessionId].tsx
=> Portal fixes

waltid-libraries/credentials/waltid-dif-definitions-parser/build.gradle.kts, waltid-libraries/credentials/waltid-verification-policies/build.gradle.kts, waltid-libraries/credentials/waltid-verification-policies/src/iosMain/kotlin/id/walt/policies/policies/RevocationPolicy.ios.kt, waltid-libraries/credentials/waltid-verification-policies/src/iosMain/kotlin/id/walt/policies/policies/SdJwtVCSignaturePolicy.ios.kt
Added iOS target to projects / missing actual empty classes
- \-
=> [iOS] add iOS target to waltid-dif-definitions-parser, walt-id-verification-policies, waltid-verifiable-credentials

waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/OpenID4VCI.kt, waltid-services/waltid-e2e-tests/src/test/resources/issuance/disclosure.json, waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/CIProvider.kt
Updates from openid refactoring branch
- [ x] new feature - change which adds functionality
- \-
=> provide w3c jwt/sd-jwt credential generation via OpenID4VCI

waltid-applications/waltid-cli/README.md, waltid-applications/waltid-cli/src/commonMain/kotlin/id/walt/cli/commands/VCVerifyCmd.kt, waltid-applications/waltid-cli/src/jvmTest/kotlin/id/walt/cli/commands/WaltIdVCVerifyCmdTest.kt, waltid-libraries/credentials/waltid-verification-policies/src/commonMain/kotlin/id/walt/policies/policies/RevocationPolicy.kt, waltid-libraries/credentials/waltid-verification-policies/src/jvmMain/kotlin/id/walt/policies/policies/RevocationPolicy.jvm.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/VerifierApi.kt, waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/VerifierApiExamples.kt
- fixes the revocation policy status bit validation
- \-
=> fix: revocation policy status bit result validation

waltid-applications/waltid-web-wallet/libs/composables/issuance.ts, waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/OpenID4VCI.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeController.kt, waltid-services/waltid-wallet-api/src/test/kotlin/id/walt/webwallet/utils/X5CValidatorTest.kt
Fix issuance CORS error in wallet.
Provide wallet API to resolve issuer metadata and use it in wallet UI
- \-
=> fix issuance CORS issue, fix x5c validator test

waltid-services/waltid-e2e-tests/src/test/kotlin/ExchangeApi.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/InputDescriptorMatchingTest.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/LspPotentialWallet.kt, waltid-services/waltid-e2e-tests/src/test/kotlin/WaltidServicesE2ETests.kt, waltid-services/waltid-wallet-api/build.gradle.kts, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/db/models/WalletCredentials.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/WalletServiceManager.kt, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/web/controllers/exchange/ExchangeController.kt
Fixed input descriptor matching on wallet API, for presentation definition.
Added some tests for credential type matching on wallet and verifier.
- \-
=> Input descriptor matching

waltid-libraries/credentials/waltid-mdoc-credentials/src/commonMain/kotlin/id/walt/mdoc/doc/MDocBuilder.kt, waltid-libraries/credentials/waltid-mdoc-credentials/src/commonMain/kotlin/id/walt/mdoc/mso/MSO.kt, waltid-libraries/credentials/waltid-mdoc-credentials/src/commonMain/kotlin/id/walt/mdoc/mso/StatusElement.kt, waltid-libraries/credentials/waltid-mdoc-credentials/src/commonMain/kotlin/id/walt/mdoc/mso/StatusListInfo.kt
Introducing StatusList element for MSO object of MDoc format according to https://www.ietf.org/archive/id/draft-ietf-oauth-status-list-03.html.
- \-
=> feat: 🎸 Introducing StatusList for MDoc

waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/usecase/event/EventLogUseCase.kt
Fixes event-log caused [error](https://gist.github.com/alegomes/413e1179671890fa3717fc12f1a76df2) related to extracting the credential type.
- \-
=> fix: get credential type according to credential format in event log use case

waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/config/CredentialTypeConfig.kt
- updates issuer metadata configuration for my_custom_vct to include clarifying name and description
closes WAL-831
- \-
=> chore: add name and description for my-custom vct in issuer metadata configuration for clarification purposes

.github/workflows/build-docker.yml, .github/workflows/build-gradle.yml, .github/workflows/build.yml, .github/workflows/changelog.yml, .github/workflows/deployment.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/test-deploy.yml, .github/workflows/version.yml, waltid-applications/waltid-web-portal/Dockerfile, waltid-services/waltid-issuer-api/Dockerfile, waltid-services/waltid-verifier-api/Dockerfile
- adds reusable workflows for:
- version (calculates the version to tag images with)
- changelog
- deployment
- gradle build
- docker build
- updates action workflows to apply the reusable ones:
- build (feature branches)
- pre-release
- release
- test-deploy (manual deployment on dev env)
- leverage matrix strategy to run jobs concurrently for:
- docker build
- deployment
closes WAL-839
- \-
=> ci: refactor reusable workflows 

.github/workflows/deployment.yml, .github/workflows/pre-release.yml, .github/workflows/test-deploy.yml
- fixes the deployment workflow:
- adds checkout step
- updates the run step for correct `sed` command call
- \-
=> ci: fix for deployment workflow to checkout repo

.github/workflows/pre-release.yml
- removes the dependency on the deploy job in the pre-release workflow
- \-
=> ci: fix leftover dependency on deploy job

.github/actions/gradle-setup-action/action.yml, .github/workflows/build-gradle.yml, .github/workflows/build.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/test-deploy.yml
=> ci: fix deprecated gradle build action

.github/workflows/release.yml, .run/Issuer.run.xml, docker-compose/.env, waltid-applications/waltid-web-portal/pages/verify/index.tsx, waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/OidcApi.kt, waltid-services/waltid-wallet-api/Dockerfile, waltid-services/waltid-wallet-api/k8s/deployment-dev.yaml
=> release 0.11.0

.github/workflows/test-deploy.yml
=> ci/cd : update deploy hash

waltid-services/waltid-verifier-api/src/main/kotlin/id/walt/verifier/oidc/VerificationUseCase.kt
=> fix: response in the usePresentationRequest

docker-compose/issuer-api/config/credential-issuer-metadata.conf, waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/config/CredentialTypeConfig.kt
=> feat: Add support for LegalPerson VC

.github/workflows/build.yml, waltid-libraries/credentials/waltid-verification-policies/build.gradle.kts, waltid-libraries/credentials/waltid-verification-policies/src/jvmMain/kotlin/id/walt/policies/policies/RevocationPolicy.jvm.kt, waltid-libraries/credentials/waltid-verification-policies/src/jvmTest/kotlin/id/walt/policies/RevocationPolicyTest.kt, waltid-libraries/waltid-did/build.gradle.kts, waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/utils/Utils.kt, waltid-services/waltid-wallet-api/src/test/kotlin/id/walt/webwallet/utils/BitstringUtilsTest.kt
=> test: revocation-policy

docker-compose/.env
Community Stack version update to 0.12.0
=> chore: Community Stack version update to 0.12.0

waltid-applications/waltid-web-portal/.env.example, waltid-applications/waltid-web-portal/.gitignore
Provide an `.env.example` file in the web-portal application.
=> chore: add example env to web portal

waltid-libraries/waltid-did/src/commonMain/kotlin/id/walt/did/dids/resolver/local/DidEbsiResolver.kt
=> fix: add content type in ebsi conformance env

waltid-libraries/credentials/waltid-w3c-credentials/src/commonMain/kotlin/id/walt/w3c/issuance/DataFunctions.kt, waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/data/DisplayProperties.kt, waltid-services/waltid-issuer-api/config/credential-issuer-metadata.conf, waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/config/CredentialTypeConfig.kt
Added secondary image to credential display
- \-
=> credential branding updates

waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/CIProvider.kt
=> fix : fix for display credential in sdjwt

waltid-applications/waltid-cli/src/jvmTest/kotlin/id/walt/cli/commands/WaltIdVCVerifyCmdTest.kt, waltid-libraries/protocols/waltid-openid4vc/src/commonMain/kotlin/id/walt/oid4vc/data/CredentialFormat.kt
=> fix: workaround for Ktor's parseQueryString

waltid-libraries/credentials/waltid-verification-policies/src/jvmTest/kotlin/id/walt/policies/policies/status/status/StatusPolicyTest.kt
- fixes status policy test data as a result of the update from #1114
relates to WAL-704
- \-
=> fix: status policy test data type

.github/workflows/pre-release.yml, .github/workflows/release.yml, .github/workflows/test-deploy.yml
Updates gradle workflow references for:
- pre-release
- release
- test-deploy
Relates to WAL-1486.
- \-
=> ci: update top-level workflows reference to gradle workflow

waltid-services/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/service/SSIKit2WalletService.kt
=> [#1087] Add support for signing flattened JWS+Json

waltid-services/waltid-service-commons/src/main/kotlin/id/walt/commons/web/modules/OpenApiModule.kt
=> fix: open api schema generation for Instant (date-time)

waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/src/components/CredentialDisclosure.vue, waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/src/pages/wallet/[wallet]/credentials/[credentialId].vue, waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/src/pages/wallet/[wallet]/exchange/presentation.vue
=> feat: Added credential selection during presentation

.github/workflows/build.yml, .github/workflows/docker-compose-testing.yml
- fixes "502 Bad Gateway" [error](https://github.com/walt-id/waltid-identity/actions/runs/16200198549/job/45736991896#step:17:23) when running docker-compose-testing workflow following #1059
- \-
=> Fix for docker compose testing workflow

waltid-libraries/waltid-did/src/jvmTest/kotlin/resolvers/DidEbsiResolverTest.kt
Add EBSI DID resolution and key validation test cases for EBSI Pilot env
- \-
=> Add EBSI DID resolution and key validation test cases for EBSI Pilot env

waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/src/pages/login.vue, waltid-applications/waltid-web-wallet/apps/waltid-demo-wallet/src/pages/signup.vue
update trusted developer count in login and signup page
=> Update developer count in login/signup pages

waltid-libraries/waltid-did/src/jvmTest/kotlin/resolvers/UniResolverTest.kt
Disables Uniresolver test cases for did cheqd and v1
- \-
=> chore: disable Uniresolver test for did-cheqd

.github/workflows/deployment.yml, .github/workflows/release.yml, .github/workflows/test-deploy.yml
Here is the working GH action working with changes - https://github.com/walt-id/waltid-identity/actions/runs/17099039018/job/48491888568
=> chore: Enterprise API deployment tag replacement

waltid-applications/waltid-openid4vc-ios-testApp/shared/src/iosMain/kotlin/id/walt/oid4vc/shared/Wallet.kt, waltid-libraries/credentials/waltid-verification-policies/src/iosMain/kotlin/id/walt/policies/policies/StatusPolicy.ios.kt, waltid-libraries/sdjwt/waltid-sdjwt-ios/build.gradle.kts, waltid-libraries/sdjwt/waltid-sdjwt-ios/src/iosTest/kotlin/SDJwtTestIOS.kt, waltid-libraries/sdjwt/waltid-sdjwt/src/nativeMain/kotlin/id/walt/sdjwt/JWTClaimsSet.kt
Fixes #1204 + additional interface update related issues with ios testApp wallet.
- \-
=> add empty status-policy definition for ios

waltid-libraries/sdjwt/waltid-sdjwt-ios/src/iosTest/kotlin/SDJwtTestIOS.kt
=> sd-jwt-ios test comment failing assertion

waltid-applications/waltid-android/build.gradle.kts, waltid-applications/waltid-cli/build.gradle.kts, waltid-libraries/credentials/waltid-mdoc-credentials/build.gradle.kts, waltid-libraries/crypto/waltid-crypto/build.gradle.kts, waltid-libraries/protocols/waltid-openid4vc/build.gradle.kts, waltid-libraries/waltid-core-wallet/build.gradle.kts, waltid-services/waltid-e2e-tests/build.gradle.kts, waltid-services/waltid-integration-tests/build.gradle.kts, waltid-services/waltid-issuer-api/build.gradle.kts, waltid-services/waltid-wallet-api/build.gradle.kts
Build was broken, because of duplicate classes in transitive dependencies of bouncycastle library
- \-
=> fix: fixed android build

waltid-services/waltid-issuer-api/src/main/kotlin/id/walt/issuer/issuance/IssuerApi.kt
=> fix: issuer did parsing in raw credential signing
